/*389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.*/

class Solution 
{
    public char findTheDifference(String s, String t) 
    { 
        char ans=' ';
        HashMap<Character,Integer> map1=new HashMap<>();
        for(int i=0; i<s.length(); i++)
        {
            if(map1.containsKey(s.charAt(i)))
                map1.put(s.charAt(i),map1.get(s.charAt(i))+1);
            else
                map1.put(s.charAt(i),1);
        }
        HashMap<Character,Integer> map2=new HashMap<>();
        for(int i=0; i<t.length(); i++)
        {
            if(map2.containsKey(t.charAt(i)))
                map2.put(t.charAt(i),map2.get(t.charAt(i))+1);
            else
                map2.put(t.charAt(i),1);
        }
        for(Map.Entry<Character,Integer> entry:map2.entrySet())
        {
            char k=entry.getKey();
            if(entry.getValue()!=map1.get(k))
            {
                ans=k;
                break;
            }
        }
        return ans;
   }
}
